import type { UnionAgreementTemplate, ObligationAnchor, ObligationRisk, ObligationType, ContractType } from './types'

export const UNION_AGREEMENT_TEMPLATES: UnionAgreementTemplate[] = [
  {
    id: 'caea-ita',
    name: 'CAEA – Integrated Theatre Agreement (ITA)',
    shortName: 'CAEA-ITA',
    union: 'Canadian Actors\' Equity Association',
    country: 'CA',
    applicableTypes: ['cast', 'creative', 'employment'],
    description: 'Covers actors, singers, dancers, and stage management working in Canadian professional theatre. Sets minimum fees, working conditions, pension contributions, and billing requirements.',
    effectiveDate: '2024-07-01',
    expiryDate: '2027-06-30',
    obligations: [
      {
        id: 'caea-ita-1',
        type: 'tax_form_required',
        description: 'TD1 personal tax credits form received from artist',
        plainEnglish: 'Before the first rehearsal, you need a completed TD1 form on file so payroll can calculate correct tax deductions.',
        anchor: 'contract_start',
        offsetDays: -7,
        risk: 'medium',
        defaultOwner: 'GM',
        clauseRef: 'ITA §36 — Payroll & Tax Documentation',
        enabledByDefault: true,
      },
      {
        id: 'caea-ita-2',
        type: 'insurance_required',
        description: 'Certificate of insurance naming CAEA on file',
        plainEnglish: 'The company must have a valid certificate of insurance (liability, errors & omissions) naming CAEA as an additional insured before rehearsals begin.',
        anchor: 'contract_start',
        offsetDays: -14,
        risk: 'high',
        defaultOwner: 'Company Manager',
        clauseRef: 'ITA §44 — Insurance',
        enabledByDefault: true,
      },
      {
        id: 'caea-ita-3',
        type: 'signature_required',
        description: 'Fully executed CAEA contract returned to Equity',
        plainEnglish: 'The signed contract must be filed with CAEA by the start of rehearsals. Late filing can result in fines and penalties.',
        anchor: 'contract_start',
        offsetDays: 0,
        risk: 'high',
        defaultOwner: 'Company Manager',
        clauseRef: 'ITA §4 — Contract Execution',
        enabledByDefault: true,
      },
      {
        id: 'caea-ita-4',
        type: 'payment_due',
        description: 'First bi-weekly fee instalment payment',
        plainEnglish: 'The artist\'s first payment instalment is due within one week of the first rehearsal day. Late payment triggers daily interest under the ITA.',
        anchor: 'contract_start',
        offsetDays: 7,
        risk: 'high',
        defaultOwner: 'Company Manager',
        clauseRef: 'ITA §24 — Payment Schedule',
        enabledByDefault: true,
      },
      {
        id: 'caea-ita-5',
        type: 'payment_due',
        description: 'CAEA pension & health fund contribution — Period 1',
        plainEnglish: 'CAEA requires pension and health fund contributions (typically 17–19% of gross fees) remitted by the 14th day after the first rehearsal week. This applies to every artist on the contract.',
        anchor: 'contract_start',
        offsetDays: 14,
        risk: 'high',
        defaultOwner: 'Company Manager',
        clauseRef: 'ITA §37 — Pension, Health & Welfare',
        enabledByDefault: true,
      },
      {
        id: 'caea-ita-6',
        type: 'approval_required',
        description: 'Billing and publicity credit approved by artist and Equity',
        plainEnglish: 'Programme, poster, and advertising copy must be approved for billing credits at least four weeks before opening. Incorrect billing can require costly reprints and carries a penalty.',
        anchor: 'opening_date',
        offsetDays: -28,
        risk: 'medium',
        defaultOwner: 'GM',
        clauseRef: 'ITA §51 — Billing & Publicity Credit',
        enabledByDefault: true,
      },
      {
        id: 'caea-ita-7',
        type: 'report_due',
        description: 'Show billing and casting report submitted to CAEA',
        plainEnglish: 'A final billing and casting report (names, roles, billing order) must be submitted to CAEA within one week of opening night.',
        anchor: 'opening_date',
        offsetDays: 7,
        risk: 'low',
        defaultOwner: 'GM',
        clauseRef: 'ITA §52 — Casting Report',
        enabledByDefault: true,
      },
      {
        id: 'caea-ita-8',
        type: 'payment_due',
        description: 'Final fee instalment payment on closing',
        plainEnglish: 'Any remaining unpaid fee balance is due on the artist\'s final day of work (closing night or last contracted day). Do not hold back final payment.',
        anchor: 'closing_date',
        offsetDays: 0,
        risk: 'high',
        defaultOwner: 'Company Manager',
        clauseRef: 'ITA §24 — Payment Schedule',
        enabledByDefault: true,
      },
      {
        id: 'caea-ita-9',
        type: 'payment_due',
        description: 'CAEA pension & health fund final contribution',
        plainEnglish: 'The final pension and health fund remittance, covering any remaining weeks of the engagement, is due within 7 days of closing.',
        anchor: 'closing_date',
        offsetDays: 7,
        risk: 'high',
        defaultOwner: 'Company Manager',
        clauseRef: 'ITA §37 — Pension, Health & Welfare',
        enabledByDefault: true,
      },
    ],
  },

  {
    id: 'afm-149',
    name: 'AFM Local 149 – Toronto Musicians',
    shortName: 'AFM 149',
    union: 'American Federation of Musicians — Local 149',
    country: 'CA',
    region: 'Ontario',
    applicableTypes: ['cast'],
    description: 'Covers musicians in the pit orchestra and on-stage for live theatre in Toronto and the surrounding region. Governs scale rates, doubling provisions, cartage, rest periods, and pension remittances.',
    effectiveDate: '2024-01-01',
    expiryDate: '2026-12-31',
    obligations: [
      {
        id: 'afm149-1',
        type: 'signature_required',
        description: 'AFM Single Engagement / Term contract filed with Local 149',
        plainEnglish: 'The fully executed AFM contract must be submitted to Local 149 at least 7 days before the first service (rehearsal or performance). Filing late can prevent musicians from working the engagement.',
        anchor: 'contract_start',
        offsetDays: -7,
        risk: 'high',
        defaultOwner: 'Company Manager',
        clauseRef: 'AFM 149 §3 — Contract Filing',
        enabledByDefault: true,
      },
      {
        id: 'afm149-2',
        type: 'approval_required',
        description: 'Doubling and additional instrument provisions confirmed in writing',
        plainEnglish: 'If any musician is being asked to play more than one instrument, the doubling fees and specific instruments must be agreed to in writing before the first service.',
        anchor: 'contract_start',
        offsetDays: -3,
        risk: 'medium',
        defaultOwner: 'GM',
        clauseRef: 'AFM 149 §11 — Doubling Provisions',
        enabledByDefault: true,
      },
      {
        id: 'afm149-3',
        type: 'payment_due',
        description: 'Scale fee payment — first service',
        plainEnglish: 'Musicians must be paid no less than the current AFM scale rate. Payment for each service period is due on the day of the service; holding pay until a later date is a contract violation.',
        anchor: 'contract_start',
        offsetDays: 0,
        risk: 'critical',
        defaultOwner: 'Company Manager',
        clauseRef: 'AFM 149 §6 — Scale Wages',
        enabledByDefault: true,
      },
      {
        id: 'afm149-4',
        type: 'payment_due',
        description: 'AFM Pension Fund contribution',
        plainEnglish: 'The employer contributes a percentage of all wages (currently 12%) to the AFM Pension Fund. This is remitted to AFM within 14 days of each payment period.',
        anchor: 'contract_start',
        offsetDays: 14,
        risk: 'high',
        defaultOwner: 'Company Manager',
        clauseRef: 'AFM 149 §18 — Pension Fund',
        enabledByDefault: true,
      },
      {
        id: 'afm149-5',
        type: 'payment_due',
        description: 'AFM Health & Welfare fund contribution',
        plainEnglish: 'Health and welfare fund contributions are due on the same schedule as pension remittances — within 14 days of each pay period.',
        anchor: 'contract_start',
        offsetDays: 14,
        risk: 'medium',
        defaultOwner: 'Company Manager',
        clauseRef: 'AFM 149 §19 — Health & Welfare',
        enabledByDefault: true,
      },
      {
        id: 'afm149-6',
        type: 'reimbursement_due',
        description: 'Cartage reimbursement for large instruments',
        plainEnglish: 'Musicians transporting large instruments (harp, bass, etc.) are entitled to cartage reimbursement. Submit receipts and process payment within 30 days of the first service.',
        anchor: 'contract_start',
        offsetDays: 30,
        risk: 'low',
        defaultOwner: 'Company Manager',
        clauseRef: 'AFM 149 §13 — Cartage',
        enabledByDefault: false,
      },
    ],
  },

  {
    id: 'sdc',
    name: 'SDC – Directors and Choreographers',
    shortName: 'SDC',
    union: 'Stage Directors and Choreographers Society',
    country: 'CA',
    applicableTypes: ['creative'],
    description: 'Governs directors and choreographers working in professional Canadian theatre. Covers advance payments, royalties, billing credit, and future production rights.',
    effectiveDate: '2023-09-01',
    expiryDate: '2026-08-31',
    obligations: [
      {
        id: 'sdc-1',
        type: 'insurance_required',
        description: 'Certificate of insurance filed before first rehearsal',
        plainEnglish: 'The company must provide a certificate of general liability insurance naming the SDC member before the first rehearsal day.',
        anchor: 'contract_start',
        offsetDays: -7,
        risk: 'medium',
        defaultOwner: 'Company Manager',
        clauseRef: 'SDC §9 — Insurance',
        enabledByDefault: true,
      },
      {
        id: 'sdc-2',
        type: 'payment_due',
        description: 'Pre-production advance payment',
        plainEnglish: 'The SDC advance (typically 25–50% of total fee) is due upon contract execution, before any pre-production work begins. This is non-refundable if the production is cancelled.',
        anchor: 'contract_start',
        offsetDays: 0,
        risk: 'critical',
        defaultOwner: 'Company Manager',
        clauseRef: 'SDC §5 — Compensation Schedule',
        enabledByDefault: true,
      },
      {
        id: 'sdc-3',
        type: 'approval_required',
        description: 'Billing credit approved — director/choreographer',
        plainEnglish: 'The director or choreographer\'s billing (font size, placement, wording) must be confirmed in writing four weeks before opening. Incorrect billing requires a correction notice in all future materials.',
        anchor: 'opening_date',
        offsetDays: -28,
        risk: 'high',
        defaultOwner: 'GM',
        clauseRef: 'SDC §14 — Billing Credit',
        enabledByDefault: true,
      },
      {
        id: 'sdc-4',
        type: 'royalty_payment',
        description: 'Opening royalty payment',
        plainEnglish: 'The per-performance royalty payments begin from opening night. The first royalty payment (covering the opening week) is typically due within 14 days of opening.',
        anchor: 'opening_date',
        offsetDays: 14,
        risk: 'high',
        defaultOwner: 'Company Manager',
        clauseRef: 'SDC §6 — Royalties',
        enabledByDefault: true,
      },
      {
        id: 'sdc-5',
        type: 'royalty_statement',
        description: 'Weekly royalty statement issued to director/choreographer',
        plainEnglish: 'A statement showing gross box office receipts and the royalty amount owed must be sent to the artist each week during the run. This is required even in weeks with no performances.',
        anchor: 'opening_date',
        offsetDays: 7,
        risk: 'medium',
        defaultOwner: 'GM',
        clauseRef: 'SDC §7 — Royalty Statements',
        enabledByDefault: true,
      },
      {
        id: 'sdc-6',
        type: 'renewal_deadline',
        description: 'Future production rights — notice period',
        plainEnglish: 'If you want to remount or transfer this production, you must notify the director/choreographer at least 30 days before closing. Failure to do so forfeits the company\'s right to future production.',
        anchor: 'closing_date',
        offsetDays: -30,
        risk: 'medium',
        defaultOwner: 'GM',
        clauseRef: 'SDC §16 — Future Production Rights',
        enabledByDefault: true,
      },
    ],
  },

  {
    id: 'iatse-58',
    name: 'IATSE Local 58 – Toronto Stagehands',
    shortName: 'IATSE 58',
    union: 'International Alliance of Theatrical Stage Employees — Local 58',
    country: 'CA',
    region: 'Ontario',
    applicableTypes: ['vendor', 'employment'],
    description: 'Covers stagehands, wardrobe, props, lighting, and sound technicians in Toronto venues. Governs minimum calls, overtime, fringe benefits, and load-in/load-out requirements.',
    effectiveDate: '2024-03-01',
    expiryDate: '2027-02-28',
    obligations: [
      {
        id: 'iatse58-1',
        type: 'compliance',
        description: 'Call schedule confirmed with Local 58 steward — 72 hrs prior',
        plainEnglish: 'IATSE requires that call schedules (who is called, for how long, and at what rate) be confirmed with the Local 58 steward at least 72 hours before each call begins. Last-minute changes can trigger penalty rates.',
        anchor: 'contract_start',
        offsetDays: -3,
        risk: 'medium',
        defaultOwner: 'Production Manager',
        clauseRef: 'IATSE 58 §8 — Call Confirmation',
        enabledByDefault: true,
      },
      {
        id: 'iatse58-2',
        type: 'payment_due',
        description: 'Minimum call payment — load-in',
        plainEnglish: 'Stagehands are entitled to a minimum 4-hour call regardless of actual time worked. Payment for load-in calls is due on the day of the call, not deferred to end of week.',
        anchor: 'contract_start',
        offsetDays: 0,
        risk: 'high',
        defaultOwner: 'Company Manager',
        clauseRef: 'IATSE 58 §11 — Minimum Call',
        enabledByDefault: true,
      },
      {
        id: 'iatse58-3',
        type: 'payment_due',
        description: 'IATSE fringe benefits — first remittance',
        plainEnglish: 'Fringe benefits (vacation pay, pension contributions) are calculated as a percentage of gross wages and remitted to IATSE Local 58 within 14 days of each pay period.',
        anchor: 'contract_start',
        offsetDays: 14,
        risk: 'high',
        defaultOwner: 'Company Manager',
        clauseRef: 'IATSE 58 §22 — Fringe Benefits',
        enabledByDefault: true,
      },
      {
        id: 'iatse58-4',
        type: 'payment_due',
        description: 'Health & welfare fund contribution',
        plainEnglish: 'Health and welfare contributions are a separate line item from fringe benefits and are submitted on the same schedule — within 14 days of each pay period.',
        anchor: 'contract_start',
        offsetDays: 14,
        risk: 'medium',
        defaultOwner: 'Company Manager',
        clauseRef: 'IATSE 58 §23 — Health & Welfare',
        enabledByDefault: true,
      },
      {
        id: 'iatse58-5',
        type: 'compliance',
        description: 'Overtime authorization submitted for calls over 8 hours',
        plainEnglish: 'Any call expected to run past 8 hours requires pre-authorized overtime approval from the production manager on file with the steward. Unauthorized overtime is still owed — but also triggers a grievance.',
        anchor: 'contract_start',
        offsetDays: 7,
        risk: 'low',
        defaultOwner: 'Production Manager',
        clauseRef: 'IATSE 58 §14 — Overtime',
        enabledByDefault: false,
      },
    ],
  },
]

export function resolveObligationDate(
  anchor: import('./types').ObligationAnchor,
  offsetDays: number,
  contractStartDate: string,
  openingDate: string,
  closingDate: string,
): string {
  const anchorDate =
    anchor === 'opening_date' ? openingDate :
    anchor === 'closing_date' ? closingDate :
    contractStartDate
  const d = new Date(anchorDate + 'T12:00:00')
  d.setDate(d.getDate() + offsetDays)
  return d.toISOString().split('T')[0]
}

export function getTemplatesForType(contractType: import('./types').ContractType): UnionAgreementTemplate[] {
  return UNION_AGREEMENT_TEMPLATES.filter(t => t.applicableTypes.includes(contractType))
}
